name: PHP Composer

on:
    push:
        branches: [ master ]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: PHP ${{ matrix.php }} - Symfony Console ${{ matrix.symfony-console }}

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                symfony-console: [ '6.0', '7.0' ]
                exclude:
                    -   php: '8.1'
                        symfony-console: '7.0'

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Validate composer.json
                run: composer validate

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Install dependencies
                run: |
                  composer require "symfony/console:^${{ matrix.symfony-console }}" --no-update
                  composer update --no-interaction --no-progress --prefer-dist

            -   name: Check style
                run: composer run-script check-style

            -   name: Run test suite
                run: composer run-script test
